[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
remappings = [
    "@solmate/=lib/solmate/"
]

[rpc_endpoints]
soneium = "${SONEIUM_RPC_URL}"
base = "${BASE_RPC_URL}"
plume = "${PLUME_RPC_URL}"
ethereum = "${ETHEREUM_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"

[etherscan]
base = { key = "${BASE_API_KEY}" }
ethereum = { key = "${ETHEREUM_API_KEY}" ,url = "https://api.etherscan.io/api" }
arbitrum = { key = "${ARBITRUM_API_KEY}" }